### ISSUE TITLE
The project is dead?

### ISSUE THREAD

**Issue by arthurcvm** [luizguilhermefr/jegueapi#1]
The project is inactive? Why?

**Comment by luizguilhermefr** [comment]
@arthurcvm That's a really good question. And it has a simple answer: Yes. Because we didn't have enough time to keep it.

**Comment by arthurcvm** [comment]
But, you can explain about the operation? Like a readme.md, I'm very interested in the application especially running in Laravel.

**Comment by luizguilhermefr** [comment]
Refer to this (PT-BR :brazil: )
[Documentação PES 2.pdf](https://github.com/luizguilhermefr/jegueapi/files/3636921/Documentacao.PES.2.pdf)
